import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import { Lock, LockClock } from "@mui/icons-material";
import Checkbox from "@mui/material/Checkbox";
import FormControlLabel from "@mui/material/FormControlLabel";
import FormControl from "@mui/material/FormControl";
import InputLabel from "@mui/material/InputLabel";
import Select from "@mui/material/Select";
import { FormHelperText, MenuItem } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>s.cr — encrypted, disposable notes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className="site-container h-screen w-screen flex flex-col md:container sm:px-12 md:px-120 md:mx-auto p-3 md:py-8 lg:px-100"
        style={{
          maxWidth: "700px",
        }}
      >
        <span className="frontmatter">
          <div className="flex items-center mb-2">
            <Link href="/">
              <Image
                width="48"
                height="48"
                alt="Icon"
                src={"/favicon.ico"}
              ></Image>
            </Link>
            <div className="ml-3">
              <h1>s.cr</h1>
              <p>Send encrypted, disposable notes</p>
            </div>
          </div>
          <p className="tagline mt-3">
            s.cr encrypts your note in your browser, so our server has no
            information about its contents. All notes expire after a period of
            time, defaulting to 24 hours.
          </p>
        </span>

        <hr style={{ marginTop: "12px", marginBottom: "16px" }} />
        <Box component="form" noValidate autoComplete="off">
          <TextField
            id="outlined-textarea"
            className="secret-text"
            fullWidth
            placeholder="Your deepest, darkest secrets go here."
            rows={10}
            multiline
          />
          <div className="flex options">
            <FormControlLabel
              className="w-1/2"
              label="Destroy after read"
              control={<Checkbox defaultChecked />}
            />

            <FormControl className="w-1/2">
              <InputLabel id="demo-simple-select-label">
                Expires after
              </InputLabel>
              <Select id="demo-simple-select" value={24} label="Expires after">
                <MenuItem value={24}>24 hours</MenuItem>
                <MenuItem value={24 * 3}>3 days</MenuItem>
                <MenuItem value={24 * 7}>7 days</MenuItem>
                <MenuItem value={24 * 30}>30 days</MenuItem>
              </Select>
            </FormControl>
          </div>
          <div className={"flex justify-between py-4"}>
            <button className="flex items-center create-button" color="success">
              <LockClock />
              Create
            </button>
          </div>
        </Box>
      </div>
    </>
  );
}
